-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    "Uid" integer,
    "Username" name[],
    "Password" character varying(12)[],
    PRIMARY KEY ("Uid")
);

COMMENT ON TABLE public."user"
    IS 'User details like
user name
Password';

CREATE TABLE IF NOT EXISTS public."Session"
(
    "Sid" integer,
    "UserID" integer,
    "Pid" integer,
    PRIMARY KEY ("Sid")
);

COMMENT ON TABLE public."Session"
    IS 'Session :- the event during which the "botanistjr" web app acesses Two CNN''s in the server
         1) Plant detection
         2) Plant Identification
        These NN''s are implemented and the results are recorded in this table';

CREATE TABLE IF NOT EXISTS public."Plants"
(
    "Pid" integer,
    "PName" name,
    "Scientific_Name" name[],
    PRIMARY KEY ("Pid")
);

CREATE TABLE IF NOT EXISTS public."User_Logins"
(
    "Logid" integer,
    "UserID" integer,
    "login_Ts" timestamp without time zone,
    "logout_Ts" timestamp with time zone,
    CONSTRAINT "LoginID" PRIMARY KEY ("Logid")
);

COMMENT ON TABLE public."User_Logins"
    IS 'When a specific user logs in and logs out from the webapp';

ALTER TABLE IF EXISTS public."Session"
    ADD CONSTRAINT "UsersID" FOREIGN KEY ("UserID")
    REFERENCES public."user" ("Uid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Session"
    ADD CONSTRAINT "PlantsID" FOREIGN KEY ("Pid")
    REFERENCES public."Plants" ("Pid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_Logins"
    ADD CONSTRAINT "User_ID" FOREIGN KEY ("UserID")
    REFERENCES public."user" ("Uid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END ;

ALTER TABLE IF EXISTS public."User_Logins"
    ALTER COLUMN "logout_Ts" TYPE timestamp without time zone;

